[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
ffi = false
fs_permissions = []
remappings = ["forge-std/=lib/forge-std/src/", "v4-core/=lib/v4-core/", "solmate/=lib/solmate/"]

[profile.default.fuzz]
runs = 512

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true
